version: '3.1'
services:
  mysql:
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3316:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: secret
volumes:
  mysql-data: