version: '3.1'
services:
  mongo:
    image: mongo:6.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27027:27017"
    volumes:
      - "mongo-data:/data/db"
volumes:
  mongo-data: