version: '3.1'
services:
  postgres:
    image: postgres:15.2
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    ports:
      - "5442:5432"
volumes:
  postgres-data: