version: '3.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - "discovery.type=single-node"
      - ELASTIC_PASSWORD=secret
    ports:
      - 9201:9200
    volumes:
      - "elasticsearch-data:/usr/share/elasticsearch/data"
volumes:
  elasticsearch-data:
