version: '3.1'
services:
  redis:
    image: redis:7.0.11-alpine
    restart: always
    ports:
      - '6389:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass secret
    volumes: 
      - redis-data:/data
volumes:
  redis-data:
